### ISSUE TITLE
Configuration re-orderes refs in an ordered relationship

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/conffwk#15]
Did not test, but it probably will do the same with values in an ordered attribute. Instead of leaving the order intact, dbe_main orders the refs/vals by id.

**Comment by glehmannmiotto** [comment]
This is a bug since the editor explicitly allows to put relations in order, but then doesn't respect the order...

**Comment by gcrone** [comment]
Having looked at the code I believe it is not a bug but a misunderstanding! The alphabetic sorting of relationships is caused by the ordered flag. To have the relationships in the order that you select in the editor the relationship must have `ordered="no"`

In oks/src/object.cpp
```
        if(r->p_ordered)
                rel_data.sort();
```

**Comment by glehmannmiotto** [comment]
ah, ok... I tried this and it works like a charm.

**Comment by eflumerf** [comment]
OK, this should probably be documented somewhere, as "ordered=yes" in the schema definitely made me think that it meant 'the order of these matters and nothing should re-order them", and "ordered=no" means "the order does not matter", when it actually means precisely the opposite!
